[openrail]
feed_username = "[replace with your own details]"
feed_password = "[replace with your own details]"

type = "service_account"
project_id = "[replace with your own details]"
private_key_id = "[replace with your own details]"
private_key = "[replace with your own details]"
client_email = "[replace with your own details]"
client_id = "[replace with your own details]"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "[replace with your own details]"