dtc_de_train:
  outputs:
    dev:
      dataset: train
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west2
      method: service-account
      priority: interactive
      project: dtc-de-project-380810
      threads: 4
      type: bigquery
  target: dev
